### ISSUE TITLE
Warning on Windows due to pandoc

### ISSUE THREAD

**Issue by nacnudus** [r-hub/rhub#64]
My vignettes fail to build on Windows, with the following error.  They pass on win-builder.

```
* checking re-building of vignette outputs ... WARNING
Error in re-building vignettes:
  ...
pandoc.exe: getAppUserDataDirectory: illegal operation (unsupported operation)
Warning: running command '"C:/PROGRA~2/Pandoc/pandoc.exe" --version' had status 1
Error: processing vignette 'tidyxl.Rmd' failed with diagnostics:
subscript out of bounds
Execution halted
```

**Comment by gaborcsardi** [comment]
This is a pandoc bug: https://github.com/jgm/pandoc/issues/3241
I'll update pandoc, and that'll fix it.

**Comment by gaborcsardi** [comment]
Should be OK now, can you please try it again? Thanks!

**Comment by nacnudus** [comment]
Fixed, thank you very much!

**Comment by aravind-j** [comment]
I am still getting the pandoc error on windows builds

`getAppUserDataDirectory: illegal operation (unsupported operation)`


`pandoc document conversion failed with error 83
   Execution halted`
